### ISSUE TITLE
Mobile Screen Support

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-farmers#6]
For supported mobile MetaMask applications, the game is not adaptive to the mobile screen size.

**Current Behaviour**

- Players can only see a portion of the farm
- Players cannot pan around the farm
- Zooming out causes a strange pattern to appear

**Expected Behaviour**

- Players can scroll around the farm and interact

![IMG_5958](https://user-images.githubusercontent.com/11745561/130393620-82b51005-db92-4c16-93ba-7949028652d9.PNG)

**Comment by Pranav-yadav** [comment]
Hey @spencerdezartsmith !
It seems you've assigned this issue to yourself 2 weeks before. Just curious about the progress :)

**Comment by adamhannigan** [comment]
@Pranav-yadav The new version has mobile support 🙏
